services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
  api:
    build: ./services/api
    container_name: body-agent-api
    env_file: .env
    environment:
      - ES_PRIVATE_INDEX=private_user_memory
      - ES_PUBLIC_INDEX=public_medical_kb
      - ES_PLACES_INDEX=providers_places
      - INTENT_EXEMPLARS_PATH=/app/seeds/intent_exemplars.json
      - INTENT_THRESHOLD=0.30
      - INTENT_MARGIN=0.05
      - INTENT_LANGS=en,he
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./services/api/app:/app/app:rw
      - ./seeds:/app/seeds:ro
      - ./services/api/app/data:/app/app/data:rw
      - ./scripts:/app/scripts:ro
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
volumes:
  es-data:
