services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
  api:
    build: ./services/api
    container_name: body-agent-api
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./services/api/app:/app/app:rw
      - ./seeds:/app/seeds:ro
      - ./docs:/app/docs:ro
      - ./data:/app/data:rw
      - ./scripts:/app/scripts:ro
      - hf-cache:/root/.cache/huggingface/hub
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
  seed:
    build: ./services/api
    container_name: body-agent-seed
    env_file: .env
    command:
      - sh
      - -lc
      - |
        set -e
        python scripts/wait_for_es.py &&
        python scripts/es_bootstrap.py &&
        python scripts/ingest_providers.py &&
        python scripts/ingest_public_kb.py
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./services/api/app:/app/app:rw
      - ./seeds:/app/seeds:ro
      - ./docs:/app/docs:ro
      - ./data:/app/data:rw
      - ./scripts:/app/scripts:ro
      - hf-cache:/root/.cache/huggingface/hub
volumes:
  es-data:
  hf-cache:
